# Generated by Django 4.2.8 on 2023-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0017_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marks",
            name="name",
            field=models.CharField(
                choices=[
                    ("Midterm 1", "Midterm 1"),
                    ("РК 1", "РК 1"),
                    ("Midterm 2", "Midterm 2"),
                    ("РК 2", "РК 2"),
                    ("Экзамен", "Экзамен"),
                ],
                default="Internal test 1",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="marksclass",
            name="name",
            field=models.CharField(
                choices=[
                    ("Midterm 1", "Midterm 1"),
                    ("РК 1", "РК 1"),
                    ("Midterm 2", "Midterm 2"),
                    ("РК 2", "РК 2"),
                    ("Экзамен", "Экзамен"),
                ],
                default="Internal test 1",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="sex",
            field=models.CharField(
                choices=[("Мужчина", "Мужчина"), ("Девушка", "Девушка")],
                default="Male",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="sex",
            field=models.CharField(
                choices=[("Мужчина", "Мужчина"), ("Девушка", "Девушка")],
                default="Male",
                max_length=50,
            ),
        ),
    ]
